Method for 'o' packet (Checking if a server is OMP)
justmavi/sampquery pull request #14
Opened 2024-10-20 19:49 UTC by markski1

### Description of change

- Adds a method for checking if a server is using open.mp or not, through a special 'o' packet.
- Does some corrections for compliance with modern .NET (stuff not marked as nullable cannot be initialized as null, etc.)
- Other changes to fix compilation issues in modern .NET (also mostly related to handling nullability in some parsing bits.)
- Small formatting changes.

Controvertial change:
- 'TryParseByte' helper, which returns a "0" on unparseable values.

This is controvertial, because returning a 0 for values that can't be parsed is illogical. The problem is that the current behaviour in these cases is crashing, and I'm not sure how else to handle it. I had certain "random" crashes on SAMonitor which stopped when I implemented this.

BE ADVISED: For some reason with my VS setup, I could not run the tests, but this version of SampQuery is currently running on [SAMonitor](https://sam.markski.ar). So I'm quite confident everything works correctly, but if someone can do the tests on their machine for me I guess that'd be better.

### Pull-Request Checklist

- [x] Code is up-to-date with the `master` branch
- [ ] All tests are passed (if tests fail due to timeout, try running the tests later or run them sequentially)
- [ ] This pull request links relevant issues as `Fixes #0000`
- [ ] There are new or updated unit tests validating the change
- [x] Documentation (README.md) has been updated to reflect this change

2024-10-20 22:38 UTC, markski1 commented
Just remembered I didn't make the changes to README, and the OMP method wrongly claims to be asynchronous. I'll fix those when I'm on my laptop.

2024-10-24 10:23 UTC, grish-st requested changes

2024-10-24 10:23 UTC, grish-st commented on Src/SampQuery.cs
> +                            else val = Helpers.TryParseByte(value, property);
This block should be refactored, properties need to be checked by name and not by type. What about `TryParseByte`, it should be tested and unit tests should be written.

2024-10-24 10:23 UTC, grish-st commented on Src/Types/ServerInfo.cs
> +        public string HostName { get; set; } = "UNKNOWN";
Why?

2024-10-24 10:23 UTC, grish-st commented on Src/Types/ServerInfo.cs
> +        public string GameMode { get; set; } = "UNKNOWN";
Why?

2024-10-24 10:23 UTC, grish-st commented on Src/Types/ServerInfo.cs
> +        public ushort Players { get; set; } = 0;
Why?

2024-10-24 10:23 UTC, grish-st commented on Src/Types/ServerInfo.cs
> +        public string Language { get; set; } = "UNKNOWN";
Why?

2024-10-24 10:23 UTC, grish-st commented on Src/Types/ServerInfo.cs
> +        public ushort MaxPlayers { get; set; } = 0;
Why?

2024-10-24 10:23 UTC, grish-st commented on Src/Types/ServerInfo.cs
> +        public bool Password { get; set; } = false;
Why?

2024-10-24 10:23 UTC, grish-st commented on Src/Types/ServerInfo.cs
> +        public int ServerPing { get; set; } = -1;
Why?

2024-10-24 10:23 UTC, grish-st commented on Src/Types/ServerPlayer.cs
> +        public string PlayerName { get; set; } = "UNKNOWN";
Why?

2024-10-24 10:23 UTC, grish-st commented on Src/Types/ServerRules.cs
> +        public string MapName { get; set; } = "UNKNOWN";
Why?

2024-10-24 10:23 UTC, grish-st commented on Src/Types/ServerRules.cs
> +        public string Version { get; set; } = "UNKNOWN";
Why?

2024-10-24 10:23 UTC, grish-st commented on Src/Types/ServerRules.cs
> +        public string SAMPCAC_Version { get; set; } = "N/A";
Why?

2024-10-24 10:23 UTC, grish-st commented on Src/Types/ServerRules.cs
> +        public Uri Weburl { get; set; } = new Uri("https://sa-mp.com");
Why?

2024-10-24 10:23 UTC, grish-st commented on Src/SampQuery.cs
> +        /// <summary>
I think you can use `SendSocketToServer`

2024-10-24 10:23 UTC, grish-st commented on Src/SampQuery.cs
> +                            else val = Helpers.TryParseByte(value, property);
Also we need the unit tests for `GetServerIsOMP` as well

2024-10-24 10:30 UTC, justmavi requested changes

2024-10-24 10:30 UTC, justmavi commented on Src/SampQuery.cs
> +        /// <summary>
I think you can use SendSocketToServer

2024-10-24 10:30 UTC, justmavi commented on Src/SampQuery.cs
> +                            else val = Helpers.TryParseByte(value, property);
This block should be refactored, properties need to be checked by name and not by type. What about TryParseByte, it should be tested and unit tests should be written.

2024-10-24 10:30 UTC, justmavi commented on Src/SampQuery.cs
> +                            else val = Helpers.TryParseByte(value, property);
Also we need the unit tests for GetServerIsOMP as well

2024-10-24 10:30 UTC, justmavi commented on Src/Types/ServerInfo.cs
> +        public string HostName { get; set; } = "UNKNOWN";
Why?

2024-10-24 10:30 UTC, justmavi commented on Src/Types/ServerInfo.cs
> +        public string GameMode { get; set; } = "UNKNOWN";
Why?

2024-10-24 10:30 UTC, justmavi commented on Src/Types/ServerInfo.cs
> +        public string Language { get; set; } = "UNKNOWN";
Why?

2024-10-24 10:30 UTC, justmavi commented on Src/Types/ServerInfo.cs
> +        public ushort Players { get; set; } = 0;
Why?

2024-10-24 10:30 UTC, justmavi commented on Src/Types/ServerInfo.cs
> +        public ushort MaxPlayers { get; set; } = 0;
Why?

2024-10-24 10:30 UTC, justmavi commented on Src/Types/ServerInfo.cs
> +        public bool Password { get; set; } = false;
Why?

2024-10-24 10:30 UTC, justmavi commented on Src/Types/ServerInfo.cs
> +        public int ServerPing { get; set; } = -1;
Why?

2024-10-24 10:30 UTC, justmavi commented on Src/Types/ServerPlayer.cs
> +        public string PlayerName { get; set; } = "UNKNOWN";
Why?

2024-10-24 10:30 UTC, justmavi commented on Src/Types/ServerRules.cs
> +        public string MapName { get; set; } = "UNKNOWN";
Why?

2024-10-24 10:30 UTC, justmavi commented on Src/Types/ServerRules.cs
> +        public string Version { get; set; } = "UNKNOWN";
Why?

2024-10-24 10:30 UTC, justmavi commented on Src/Types/ServerRules.cs
> +        public string SAMPCAC_Version { get; set; } = "N/A";
Why?

2024-10-24 10:30 UTC, justmavi commented on Src/Types/ServerRules.cs
> +        public Uri Weburl { get; set; } = new Uri("https://sa-mp.com");
Why?

2024-10-24 10:33 UTC, justmavi commented
Hello, @markski1 !
Thank you for your PR. I wrote some comments and requested some changes on code, please check.
And also let's discuss, which servers are you sending a request to and getting an exception?

2024-10-24 10:42 UTC, justmavi commented
Could you provide any references to `open.mp` query mechanism?

2024-10-24 14:07 UTC, markski1 commented
Hi, I'll be checking the comments in more detail later in the day

To respond to some of the broader questions:

- The season for "UKNOWN" string is that the version of .NET I was writing on does not allow defining those variables without either making them nullable or assigning them any value on declaration.
- I don't have saved any of the servers that caused this failure, but I can try and run a version that logs the caught exceptions and make a list.
- The query mechanism has no documentation, I'll post a reference to the code I took it from when I review the other stuff, I'd have to find it first

2024-10-26 07:00 UTC, markski1 commented
I've been busy with work but I gave it some attention today.

I installed the correct .NET versions now, and realize that my changes to defaults and nullable stuff were unnecesary, so I've now undone them.

I made some small tweaks (simple 'using' syntax for writer and such) and made a change to use SendSocketToServer which seems to work on a script.

Currently I am struggling to make the VS test tooling work on my computer for some reason. I must sort that out.

As such, I guess this is my TODO:

- Refactor the block within `CollectServerRulesFromByteArray` to grab types by their name.
- Sort out the test stuff in my VS install.
- Create unit test(s) for TryParseByte.
- Create unit test(s) for GetServerIsOMP.
- Possibly update existing tests (they seem to use server IPs that are no longer online).
- Pass the tests.

2024-12-04 01:18 UTC, markski1 commented
I will not be finishing this.

2024-12-04 01:18 UTC, closed without merging